# Generated by Django 5.0 on 2023-12-27 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog-photos/%Y/%m/%d"
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=200, null=True)),
                ("tags", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "card_description",
                    models.CharField(default="somevalue", max_length=300),
                ),
                ("body", models.TextField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=200)),
                ("github", models.URLField()),
                ("demo", models.URLField(blank=True)),
                ("image", models.FileField(blank=True, upload_to="project-photos/")),
                ("show", models.BooleanField(default=False)),
            ],
        ),
    ]
